// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/89349080150d5a3369a2f63151add48b6b550b42/redux-promise/redux-promise.d.ts
declare namespace ReduxPromise {
    export interface Promise extends Redux.Middleware {}
    export interface PromiseInterface {
      <T>(dispatch: Redux.Dispatch, getState?: () => T): any;
    }
}

declare module "redux-promise" {
    var promise: ReduxPromise.Promise;
    export default promise;
}